# version: '3.8'

services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
  #    - ./nodered_data/settings.js:/data/settings.js
    restart: unless-stopped
    networks:
      - iot_net

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=telecom-2025*
      - DOCKER_INFLUXDB_INIT_ORG=tce-iot-server
      - DOCKER_INFLUXDB_INIT_BUCKET=telecom-sensor-DB
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=tce-admin-2025
    restart: unless-stopped
    networks:
      - iot_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana_data:/var/lib/grafana

      # Try to permission acces with command "sudo chown -R 472:472 ./grafana_data"

    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - iot_net

networks:
  iot_net:
    driver: bridge
